### ISSUE TITLE
Login will not work

### ISSUE THREAD

**Issue by edo0** [nixton9/HomePage#3]
I have followed the instructions to the letter and deployed the homepage on Heroku, initially through the CLI client, and later through Github connection (setting vars in Heroku).
[The instance is running](https://startpage-it.herokuapp.com/), but not matter what, in spite of having set up the password with REACT_APP_LOGIN_KEY variable, it will not let me in.

**Comment by nixton9** [comment]
Have you added the ENV variables on the Heroku config vars section?

**Comment by edo0** [comment]
Yes, I did add them before making Heroku build it
```
heroku config -a startpage-it
 ›   Warning: heroku update available from 7.42.8 to 7.42.13.
=== startpage-it Config Vars
REACT_APP_GOOGLE_API_KEY:   ******************************
REACT_APP_GOOGLE_CLIENT_ID: *************************
REACT_APP_LOGIN_KEY:        **********
REACT_APP_MOVIES_API_KEY:   **********************************
REACT_APP_NEWS_API_KEY:     ******************************
REACT_APP_TIINGO_KEY:       ***************************
REACT_APP_WEATHER_API_KEY:  **************************


```

**Comment by edo0** [comment]
Nor did I change any part of your code in my [repo](https://github.com/edo0/HomePage), except for the country code in news.js

**Comment by edo0** [comment]
Not sure if this may help, but this is the activity log from Heroku
![Screenshot_2020-08-31_11-54-22](https://user-images.githubusercontent.com/16632292/91707940-daf43480-eb80-11ea-840d-c47b1101a358.png)

And this a complete log of the web instance

```
2020-08-31T09:56:56.370533+00:00 heroku[router]: at=info method=GET path="/precache-manifest.f9ef07f1309c9730b727abca944a065e.js" host=startpage-it.herokuapp.com request_id=9bf57784-4f8b-4952-8957-f10c61ea24a9 fwd="5.170.34.171" dyno=web.1 connect=1ms service=3ms status=304 bytes=347 protocol=https
2020-08-31T09:56:56.705918+00:00 heroku[router]: at=info method=GET path="/" host=startpage-it.herokuapp.com request_id=4167bc18-c74c-4ac1-9333-843b8b9b00bb fwd="5.170.34.171" dyno=web.1 connect=0ms service=2ms status=304 bytes=347 protocol=https
2020-08-31T09:56:56.735881+00:00 heroku[router]: at=info method=GET path="/manifest.json" host=startpage-it.herokuapp.com request_id=fa6aee5d-4c34-4a08-9cd3-fcfb5507d2e4 fwd="5.170.34.171" dyno=web.1 connect=0ms service=1ms status=304 bytes=347 protocol=https
2020-08-31T09:56:56.817550+00:00 heroku[router]: at=info method=GET path="/logo192.png" host=startpage-it.herokuapp.com request_id=da51f981-fb4c-4dae-a0e2-bc39deafae57 fwd="5.170.34.171" dyno=web.1 connect=1ms service=1ms status=304 bytes=348 protocol=https
2020-08-31T09:56:57.356382+00:00 heroku[router]: at=info method=GET path="/" host=startpage-it.herokuapp.com request_id=0a51a7f8-e668-4a93-8c2e-0a05cea4beee fwd="5.170.34.171" dyno=web.1 connect=0ms service=5ms status=200 bytes=2883 protocol=https
2020-08-31T09:56:57.586302+00:00 heroku[router]: at=info method=GET path="/static/css/main.a12f2e85.chunk.css" host=startpage-it.herokuapp.com request_id=e0d8fcf5-c9b6-413e-a620-fdd79202c647 fwd="5.170.34.171" dyno=web.1 connect=0ms service=3ms status=200 bytes=2505 protocol=https
2020-08-31T09:56:57.886168+00:00 heroku[router]: at=info method=GET path="/static/js/main.9f2681f0.chunk.js" host=startpage-it.herokuapp.com request_id=d48b98b0-665e-499f-a068-5d4361e6721a fwd="5.170.34.171" dyno=web.1 connect=0ms service=6ms status=200 bytes=85882 protocol=https
2020-08-31T09:56:57.917217+00:00 heroku[router]: at=info method=GET path="/static/js/2.90fbfbcb.chunk.js" host=startpage-it.herokuapp.com request_id=bbc54368-23a5-4975-86ae-b60f8a2da3d9 fwd="5.170.34.171" dyno=web.1 connect=1ms service=31ms status=200 bytes=816027 protocol=https
2020-08-31T09:56:59.437939+00:00 heroku[router]: at=info method=GET path="/" host=startpage-it.herokuapp.com request_id=59993538-1410-457b-ac2e-47edd555a7ef fwd="5.170.34.171" dyno=web.1 connect=0ms service=3ms status=304 bytes=347 protocol=https
2020-08-31T09:57:00.372199+00:00 heroku[router]: at=info method=GET path="/manifest.json" host=startpage-it.herokuapp.com request_id=59e95e40-22f5-4ac1-a66b-db75486b9d5d fwd="5.170.34.171" dyno=web.1 connect=0ms service=2ms status=304 bytes=347 protocol=https
2020-08-31T09:57:00.372278+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=startpage-it.herokuapp.com request_id=1b7feafd-b256-4078-a2c2-95782728428c fwd="5.170.34.171" dyno=web.1 connect=0ms service=2ms status=200 bytes=1537 protocol=https
2020-08-31T09:57:00.461028+00:00 heroku[router]: at=info method=GET path="/logo192.png" host=startpage-it.herokuapp.com request_id=588b94de-ef3d-430a-a9c7-b697389ebe9f fwd="5.170.34.171" dyno=web.1 connect=0ms service=1ms status=304 bytes=348 protocol=https
```

**Comment by nixton9** [comment]
Have you tried running this locally?

**Comment by edo0** [comment]
Locally (Arch Linux), I do have `npm` installed, but I may be missing something else
This is the full npm debug log (tried a few times, the result is always this)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.7
3 info using node@v14.9.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle homepage@1.0.0~predev: homepage@1.0.0
6 info lifecycle homepage@1.0.0~dev: homepage@1.0.0
7 verbose lifecycle homepage@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle homepage@1.0.0~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/username/Startpage/HomePage-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/username/.cargo/bin/:/home/username/.local/bin
9 verbose lifecycle homepage@1.0.0~dev: CWD: /home/username/Startpage/HomePage-master
10 silly lifecycle homepage@1.0.0~dev: Args: [ '-c', 'concurrently --kill-others "npm run start" "npm run client"' ]
11 info lifecycle homepage@1.0.0~dev: Failed to exec dev script
12 verbose stack Error: homepage@1.0.0 dev: `concurrently --kill-others "npm run start" "npm run client"`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:314:20)
12 verbose stack     at maybeClose (internal/child_process.js:1047:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid homepage@1.0.0
14 verbose cwd /home/username/Startpage/HomePage-master
15 verbose Linux 5.8.5-zen1-1-zen
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
17 verbose node v14.9.0
18 verbose npm  v6.14.7
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error homepage@1.0.0 dev: `concurrently --kill-others "npm run start" "npm run client"`
23 error spawn ENOENT
24 error Failed at the homepage@1.0.0 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by edo0** [comment]
Ok, so I have found in the other thread about `npm install`.
This is its output:

```
npm install

> puppeteer@3.1.0 install /home/edoardo/Startpage/HomePage-master/node_modules/puppeteer
> node install.js

Downloading Chromium r756035 - 125.2 Mb [====================] 100% 0.0s 
Chromium (756035) downloaded to /home/edoardo/Startpage/HomePage-master/node_modules/puppeteer/.local-chromium/linux-756035

> core-js@2.6.11 postinstall /home/edoardo/Startpage/HomePage-master/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> nodemon@2.0.4 postinstall /home/edoardo/Startpage/HomePage-master/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN homepage@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 334 packages from 232 contributors and audited 335 packages in 134.153s

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

But then running `npm run dev` I would get
```
npm run dev

> homepage@1.0.0 dev /home/edoardo/Startpage/HomePage-master
> concurrently --kill-others "npm run start" "npm run client"

[0] 
[0] > homepage@1.0.0 start /home/edoardo/Startpage/HomePage-master
[0] > npm install && node server.js
[0] 
[1] 
[1] > homepage@1.0.0 client /home/edoardo/Startpage/HomePage-master
[1] > cd client && npm start
[1] 
[1] 
[1] > homepage@0.1.0 start /home/edoardo/Startpage/HomePage-master/client
[1] > react-scripts start
[1] 
[1] sh: react-scripts: command not found
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! syscall spawn
[1] npm ERR! file sh
npm ERR! errno ENOENT
[1] npm ERR! homepage@0.1.0 start: `react-scripts start`
[1] npm ERR! spawn ENOENT
[1] npm ERR! 
[1] npm ERR! Failed at the homepage@0.1.0 start script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/edoardo/.npm/_logs/2020-08-31T15_29_26_874Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! homepage@1.0.0 client: `cd client && npm start`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the homepage@1.0.0 client script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/edoardo/.npm/_logs/2020-08-31T15_29_26_919Z-debug.log
[1] npm run client exited with code 1
--> Sending SIGTERM to other processes..
[0] npm run start exited with code 0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homepage@1.0.0 dev: `concurrently --kill-others "npm run start" "npm run client"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homepage@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/edoardo/.npm/_logs/2020-08-31T15_29_27_205Z-debug.log
```

The full log contains

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.7
3 info using node@v14.9.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle homepage@1.0.0~predev: homepage@1.0.0
6 info lifecycle homepage@1.0.0~dev: homepage@1.0.0
7 verbose lifecycle homepage@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle homepage@1.0.0~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/edoardo/Startpage/HomePage-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/edoardo/.cargo/bin/:/home/edoardo/.local/bin
9 verbose lifecycle homepage@1.0.0~dev: CWD: /home/edoardo/Startpage/HomePage-master
10 silly lifecycle homepage@1.0.0~dev: Args: [ '-c', 'concurrently --kill-others "npm run start" "npm run client"' ]
11 silly lifecycle homepage@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle homepage@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: homepage@1.0.0 dev: `concurrently --kill-others "npm run start" "npm run client"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid homepage@1.0.0
15 verbose cwd /home/edoardo/Startpage/HomePage-master
16 verbose Linux 5.8.5-zen1-1-zen
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v14.9.0
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 1
22 error homepage@1.0.0 dev: `concurrently --kill-others "npm run start" "npm run client"`
22 error Exit status 1
23 error Failed at the homepage@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by nixton9** [comment]
Hmm, can you try the solutions shown here? https://stackoverflow.com/questions/47928735/react-scripts-is-not-recognized-as-an-internal-or-external-command

**Comment by edo0** [comment]
I have made some progress. What I needed to do was:
1) `npm install react-scripts --save`
2) `npm install typescript`
Now, running `npm install`, everything seems to work out fine, only few warnings but no error messages 

When finally running `npm run dev`, the browser is opened on `http://localhost:3000/` , but unfortunately an error message pops up on the webpage

> Failed to compile
> `./src/blocks/dribbble/DribbbleContainer.tsx`
>   `Line 0:  Parsing error: Cannot read property 'map' of undefined`
> This error occurred during the build time and cannot be dismissed.

Meanwhile, the terminal shows

```
npm run dev

> homepage@1.0.0 dev /home/edoardo/Startpage/All Others/HomePage-master
> concurrently --kill-others "npm run start" "npm run client"

[0] 
[0] > homepage@1.0.0 start /home/edoardo/Startpage/All Others/HomePage-master
[0] > npm install && node server.js
[0] 
[1] 
[1] > homepage@1.0.0 client /home/edoardo/Startpage/All Others/HomePage-master
[1] > cd client && npm start
[1] 
[1] 
[1] > homepage@0.1.0 start /home/edoardo/Startpage/All Others/HomePage-master/client
[1] > react-scripts start
[1] 
[1] ℹ ｢wds｣: Project is running at http://192.168.0.182/
[1] ℹ ｢wds｣: webpack output is served from 
[1] ℹ ｢wds｣: Content not from webpack is served from /home/edoardo/Startpage/All Others/HomePage-master/client/public
[1] ℹ ｢wds｣: 404s will fallback to /
[1] Starting the development server...
[1] 
[1] Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
[0] npm WARN mini-create-react-context@0.4.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-icons@3.10.0 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-resize-detector@2.3.0 requires a peer of react@^0.14.7 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-router@5.2.0 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-router-dom@5.2.0 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-smooth@1.0.5 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-smooth@1.0.5 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-transition-group@2.9.0 requires a peer of react@>=15.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-transition-group@2.9.0 requires a peer of react-dom@>=15.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN recharts@1.8.5 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN recharts@1.8.5 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN homepage@1.0.0 No repository field.
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
[0] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
[0] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/react-scripts/node_modules/fsevents):
[0] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
[0] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
[0] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] 
[1] Failed to compile.
[1] 
[1] ./src/blocks/dribbble/DribbbleContainer.tsx
[1]   Line 0:  Parsing error: Cannot read property 'map' of undefined
[1] Compiling...
[0] up to date in 30.85s
[1] Failed to compile.
[1] 
[1] ./src/blocks/dribbble/DribbbleContainer.tsx
[1]   Line 0:  Parsing error: Cannot read property 'map' of undefined
[0] 
[0] 74 packages are looking for funding
[0]   run `npm fund` for details
[0] 
[0] Homepage running on Port 8000

```

**Comment by nixton9** [comment]
Hey! So I just tried running this on a different computer and I was able to reproduce the errors you were having and saw what was wrong. I updated the readme file with a 'How to' guide. Follow it from the beginning and everything should be fine now! Let me know if you have any problems with it :)

**Comment by edo0** [comment]
Hi again! Thank you very much for updating the installation instructions!!
Now I am capable of deploying it seemingly correctly ...
```
npm run dev

> homepage@1.0.0 dev /home/edoardo/Startpage/All Others/HomePage-master
> concurrently --kill-others "npm run start" "npm run client"

[0] 
[0] > homepage@1.0.0 start /home/edoardo/Startpage/All Others/HomePage-master
[0] > npm install && node server.js
[0] 
[1] 
[1] > homepage@1.0.0 client /home/edoardo/Startpage/All Others/HomePage-master
[1] > cd client && npm start
[1] 
[1] 
[1] > homepage@0.1.0 start /home/edoardo/Startpage/All Others/HomePage-master/client
[1] > react-scripts start
[1] 
[1] ℹ ｢wds｣: Project is running at http://192.168.183.67/
[1] ℹ ｢wds｣: webpack output is served from 
[1] ℹ ｢wds｣: Content not from webpack is served from /home/edoardo/Startpage/All Others/HomePage-master/client/public
[1] ℹ ｢wds｣: 404s will fallback to /
[1] Starting the development server...
[1] 
[1] Files successfully emitted, waiting for typecheck results...
[1] Compiled successfully!
[1] 
[1] You can now view homepage in the browser.
[1] 
[1]   Local:            http://localhost:3000
[1]   On Your Network:  http://192.168.183.67:3000
[1] 
[1] Note that the development build is not optimized.
[1] To create a production build, use npm run build.
[1] 
[0] npm WARN mini-create-react-context@0.4.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-icons@3.10.0 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-resize-detector@2.3.0 requires a peer of react@^0.14.7 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-router@5.2.0 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-router-dom@5.2.0 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-smooth@1.0.5 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-smooth@1.0.5 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-transition-group@2.9.0 requires a peer of react@>=15.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN react-transition-group@2.9.0 requires a peer of react-dom@>=15.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN recharts@1.8.5 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN recharts@1.8.5 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
[0] npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
[0] npm WARN homepage@1.0.0 No repository field.
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
[0] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
[0] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/react-scripts/node_modules/fsevents):
[0] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
[0] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0] 
[0] audited 1912 packages in 28.42s
[0] 
[0] 74 packages are looking for funding
[0]   run `npm fund` for details
[0] 
[0] found 0 vulnerabilities
[0] 
[0] Homepage running on Port 8000
```
... however, I find myself in the same situation as with [heroku](https://startpage-it.herokuapp.com/), in which I can see the homepage, but it will not accept my password set as per the `.env` file.

**Comment by tphjsz** [comment]
> ... however, I find myself in the same situation as with [heroku](https://startpage-it.herokuapp.com/), in which I can see the homepage, but it will not accept my password set as per the `.env` file.

I had the same problem. It wouldn't accept any password set in the .env file, so I went to the login.tsx file and changed  
`if (password === APP_PASSWORD) {  `
to 
 `if (password !== APP_PASSWORD) {`
That would let me in if the password didn't match the .env file (I was just testing around). Then I changed it back to the way it was before and now it works with the password set in the .env file. Dunno why lol

**Comment by edo0** [comment]
Mmmh. 
Setting 
`if (password !== APP_PASSWORD) {` 
does allow me to access the HomePage with any wrong password, but unfortunately reverting to 
`if (password !== APP_PASSWORD) {`
will just me lock out again (after cleaning browser data / trying to access from another browser).

**Comment by nixton9** [comment]
@edo0 @tphjsz Is this problem happening locally and in Heroku? Or only on Heroku?

**Comment by edo0** [comment]
Both locally and on Heroku for me

**Comment by nixton9** [comment]
> Both locally and on Heroku for me

Hmm, that's very strange then. Try putting a console.log for the password you input and another for the APP_PASSWORD, both before that verification, and check if you're seeing exactly the same value

**Comment by PeterKetzer** [comment]
> > Both locally and on Heroku for me
> 
> Hmm, that's very strange then. Try putting a console.log for the password you input and another for the APP_PASSWORD, both before that verification, and check if you're seeing exactly the same value

Hi @nixton9 , I'm facing the same issue, however I have little knowledge in programming, so I don't know if this gif will help you: 
![deepin-screen-recorder_Select area_20201017225000](https://user-images.githubusercontent.com/37319386/96356915-4c555b80-10cb-11eb-96d4-2eeb3cbb56cd.gif)

**Comment by nixton9** [comment]
> > > Both locally and on Heroku for me
> > 
> > 
> > Hmm, that's very strange then. Try putting a console.log for the password you input and another for the APP_PASSWORD, both before that verification, and check if you're seeing exactly the same value
> 
> Hi @nixton9 , I'm facing the same issue, however I have little knowledge in programming, so I don't know if this gif will help you:
> ![deepin-screen-recorder_Select area_20201017225000](https://user-images.githubusercontent.com/37319386/96356915-4c555b80-10cb-11eb-96d4-2eeb3cbb56cd.gif)

Did you add the env variable for the password?

**Comment by PeterKetzer** [comment]
@nixton9 , yes:


![deepin-screen-recorder_gedit_20201019212656](https://user-images.githubusercontent.com/37319386/96525878-7a18dc80-1252-11eb-8fbe-031f118592e9.gif)

**Comment by nixton9** [comment]
> @nixton9 , yes:
> 
> ![deepin-screen-recorder_gedit_20201019212656](https://user-images.githubusercontent.com/37319386/96525878-7a18dc80-1252-11eb-8fbe-031f118592e9.gif)

Hmmm this is really strange. Did you fork this repo or something? Would like to take a look at your code

**Comment by PeterKetzer** [comment]
> > @nixton9 , yes:
> > ![deepin-screen-recorder_gedit_20201019212656](https://user-images.githubusercontent.com/37319386/96525878-7a18dc80-1252-11eb-8fbe-031f118592e9.gif)
> 
> Hmmm this is really strange. Did you fork this repo or something? Would like to take a look at your code

I downloaded it through the terminal, here is a Drive link with all of my archives: https://drive.google.com/file/d/1A8f89XDLcab_qxF-h2WgwJdZoYCGu-Hf/view?usp=sharing

**Comment by nixton9** [comment]
Hey @PeterKetzer so the problem is that your file is named 'config.env' when it should be only '.env'. Fix that, make sure your restart the app and it should be all good!

Also, console.log() won't work there because it is not a javascript file

**Comment by PeterKetzer** [comment]
Ah, so that was the problem, it worked now! Thanks!

About console.log(), as I said, I'm still learning, hahaha

Thanks once more!
